const actionTypes = {
	ADD_RESERVATION: 'ADD_RESERVATION',
	LOAD_RESERVATIONS: 'LOAD_RESERVATIONS',
	FILTER_RESERVATIONS_BY_UUID: 'FILTER_RESERVATIONS_BY_UUID',
	CHANGE_CURRENCY: 'CHANGE_CURRENCY'
};

export default actionTypes;
